baseURL = "https://cancms2030.github.io/"
languageCode = "zh-cn"
title = "CANCMS"
theme = "cancms"

[params]
  description = "为您提供最专业的网站建设服务"
  keywords = "网站建设,网站开发,管理系统应用开发,UI设计"
  author = "CANCMS"
  company = "CANCMS"
  address = ""
  phone = ""
  email = "cancms@163.com"
  taobao_shop = "https://item.taobao.com/item.htm?id=767084316219"
  weixin = "ncp2025"

[menus]
  [[menus.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menus.main]]
    identifier = "about"
    name = "关于我们"
    url = "/about/"
    weight = 2
 

  [[menus.main]]
    identifier = "services"
    name = "我们的服务"
    url = "/services/"
    weight = 3
  
  [[menus.main]]
    identifier = "portfolio"
    name = "案例展示"
    url = "/portfolio/"
    weight = 4
 
  [[menus.main]]
    identifier = "blog"
    name = "博客"
    url = "/blog/"
    weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"] 